### ISSUE TITLE
match device['productType'] SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lboue** [AngelIV23/Meraki-To-MindMaps#2]
Hello,

```
I am getting an error with Python 3.9.2 when I start your script:
(myvenv) user@raspberrypi:~/Meraki-To-MindMaps $ python meraki_api_main.py 
Traceback (most recent call last):
  File "/home/user/Meraki-To-MindMaps/meraki_api_main.py", line 13, in <module>
    from meraki_functions import *
  File "/home/user/Meraki-To-MindMaps/meraki_functions.py", line 78
    match device['productType']:
          ^
SyntaxError: invalid syntax
```

Could you tell me how to fix that?

Regards

**Comment by ainglese-dev** [comment]
please, I kindly request to send me the output for that variable, probably you have a product which is not valid for this code and is required to be adapted. Follow next steps to debug:

step 1. git pull the project.
step 2. switch to branch 'issue#2' 
step 3. Run the command: python meraki_api_main.py
step 4. Please check if device_list var is returning a list or a dict and corresponding result, since it is required to have a key as 'productType' (probably my testings doesn't contain same key pairs)

thanks.

**Comment by lboue** [comment]
I found the issue. Structural Pattern Matching has been introduced with Python 3.10. 
So you have to make Python =>3.10 as requirement.

Regards

**Comment by lboue** [comment]
Maybe you can use this snippet to check Python version:

```
import sys
import warnings

def checkVersion():
    # Checking Python version:
    expect_major = 3
    expect_minor = 10
    expect_rev = 14
    if sys.version_info[:2] != (expect_major, expect_minor):
        print("INFO: Script developed and tested with Python " + str(expect_major) + "." + str(expect_minor))
        current_version = str(sys.version_info[0])+"."+str(sys.version_info[1])
        if sys.version_info[:2] != (expect_major, expect_minor):
            warnings.warn("Current Python version was unexpected: Python " + current_version)
        else:
            print("      Current version is different: Python " + current_version)

checkVersion()
```

**Comment by ainglese-dev** [comment]
I'll update this PR in a couple of days, since I need more time to test on replicate issue in dev environments.
