### ISSUE TITLE
AttributeError: 'Console' object has no attribute 'save_svg'

### ISSUE THREAD

**Issue by lboue** [AngelIV23/Meraki-To-MindMaps#3]
Hello Angel,

I am facing an issue with you script with this setup:
- Python3.10

```
C:/Users/user/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/user/Documents/Projets/Automation/VScode/repo/Meraki-To-MindMaps/meraki_api_main.py"

2022-08-24 10:47:36,556 [INFO] Loading API_KEY to system.
2022-08-24 10:47:36,557 [WARNING] Using default Meraki Always-On API KEY, create .env file for private key.
2022-08-24 10:47:36,558 [INFO] Gathering Organizations from Meraki via API
2022-08-24 10:47:37,586 [INFO] Initializing md file under outputs folder
2022-08-24 10:47:37,587 [INFO] Collecting licensing via API per 34 company(ies)
|####################################################################################################| 100.00%
2022-08-24 10:48:43,549 [INFO] Creating SVG file from collected data
                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      |             Org ID |                    Client Name | Licensing Status | Expiration date | licensed Devices |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      |             865776 |             Cisco Live US 2019 |  License Expired |      2020-07-15 |  "MS120-8FP": 10 |

                      |                    |                                |                  |                 |         "MV": 10 |

                      |                    |                                |                  |                 |       "MX67": 10 |

                      |                    |                                |                  |                 |   "wireless": 10 |

                      |                    |                                |                  |                 |         "Z3C": 2 |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      |              52636 |            Forest City - Other |               OK |      2024-08-18 |   "wireless": 20 |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      |             681155 |                          DeLab |               OK |      2024-10-13 |   "wireless": 40 |

                      |                    |                                |                  |                 |    "MS220-8P": 9 |

                      |                    |                                |                  |                 |        "MX65": 6 |

                      |                    |                                |                  |                 |          "MC": 4 |

                      |                    |                                |                  |                 |          "MV": 9 |

                      |                    |                                |                  |                 |     "MS220-8": 1 |

                      |                    |                                |                  |                 |          "SM": 5 |

                      |                    |                                |                  |                 |       "MX250": 1 |

                      |                    |                                |                  |                 |  "MS250-48FP": 1 |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 566327653141842188 |                    DevNetAssoc |               OK |      2025-01-31 |   "MS120-8FP": 1 |

                      |                    |                                |                  |                 |    "MS250-24": 1 |

                      |                    |                                |                  |                 |  "MS350-48LP": 1 |

                      |                    |                                |                  |                 |    "MS410-16": 1 |

                      |                    |                                |                  |                 |    "MS425-32": 1 |

                      |                    |                                |                  |                 |          "MV": 5 |

                      |                    |                                |                  |                 |       "MX100": 1 |

                      |                    |                                |                  |                 |       "MX450": 1 |

                      |                    |                                |                  |                 |        "MX67": 1 |

                      |                    |                                |                  |                 |       "MX68W": 1 |

                      |                    |                                |                  |                 |         "Z3C": 1 |

                      |                    |                                |                  |                 |    "wireless": 5 |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      |             463308 |                        Hi Cory |               OK |      2025-11-21 |        "MX60": 5 |

                      |                    |                                |                  |                 |        "MX65": 3 |

                      |                    |                                |                  |                 |          "MV": 8 |

                      |                    |                                |                  |                 |   "MS220-24P": 5 |

                      |                    |                                |                  |                 |  "MS220-48FP": 2 |

                      |                    |                                |                  |                 |    "wireless": 8 |

                      |                    |                                |                  |                 |   "MS220-8P": 10 |

                      |                    |                                |                  |                 |          "MC": 1 |

                      |                    |                                |                  |                 |        "SM": 101 |

                      |                    |                                |                  |                 |       "MX67C": 1 |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      |             549236 |                 DevNet Sandbox | License Required |      2029-07-07 |    "MS220-8P": 1 |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 573083052582914233 | organization with name changed |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 573083052582914605 |                 Jacks_test_net |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 573083052582915028 |                Next Meraki Org |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 573083052582915123 |                     BCX-Ithala |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 573083052582915124 |                     BCX-Telkom |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582591 |           Ftreqah organization |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582684 |                            SVR |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582738 |                My organization |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582755 |              Your Organization |              N/A |             N/A |            "N/A" |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582756 |              Personal.Lekhnath |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582973 |                DevNet Test Org |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396582986 |                DevNet Test Org |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583031 |                My organization |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583051 |                        Hi Cory |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583071 |                        PM_Test |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583093 |                   DevNet's Org |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583128 |                             gk |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583131 |                       thienbao |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583133 |                        Hi Cory |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583134 |                          Wotan |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583158 |                        Testlab |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583197 |                     Sample Org |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583213 |                 sample_network |              N/A |             N/A |            "N/A" |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583237 |                     changetest |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583264 |                My organization |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583536 |      TNF - The Network Factory |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583708 |                     helloworld |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

                      | 575334852396583819 |                          test5 |               OK |             N/A |                  |

                      +--------------------+--------------------------------+------------------+-----------------+------------------+

Traceback (most recent call last):

  File "c:\Users\user\OneDrive - GFI\Documents\Projets\Automation\VScode\repo\Meraki-To-MindMaps\meraki_api_main.py", line 89, in <module>

    table_svg(pTable, "fullTable_licensing")

  File "c:\Users\user\OneDrive - GFI\Documents\Projets\Automation\VScode\repo\Meraki-To-MindMaps\meraki_functions.py", line 47, in table_svg        

    console.save_svg(f"outputs/{filename}.svg", title=filename)

AttributeError: 'Console' object has no attribute 'save_svg'
```

**Comment by ainglese-dev** [comment]
Issue closed by requirements.txt file updated :)
